### ISSUE TITLE
Adding required to submit

### ISSUE THREAD

**Issue by jenath** [fac-14/team4week2#17]
https://github.com/fac-14/team4week2/blob/791fdbd7c8a0a6103f2863107a295131248e1bcd/index.html#L20

`<input type="text" name="description" value="" required>`

- You can add a **required** attribute to the input tag this will prevent items with no value being added onto the to-do list.

![2](https://user-images.githubusercontent.com/28295599/42684002-d1cf1124-8686-11e8-9279-f71aae8d2c6d.png)

**Comment by sunuwars** [comment]
thanks Jeanath :smiley: that was such a helpful tip . Implemented it :sparkles:
