### ISSUE TITLE
Testing the original array

### ISSUE THREAD

**Issue by thejoefriel** [fac-14/team4week2#22]
I can't find a test that checks that you're not altering the original todos array that you're feeding into your functions. 

In terms of achieving lovely 'pure functions' your functions should not be altering the original array, but looking at your code I think you are altering the original array. 

So you need to build a test to ensure the original array remains unchanged and modify your functions so they then pass this test. I believe we've done this (🤞 ), so if you need any help just holla!

**Comment by sunuwars** [comment]
Thanks Joe :smiley: yes we realise that now  :sweat_smile:  we will definitely to do it the right way after this
